# Generated by Django 3.1.7 on 2021-03-11 19:08
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinamicform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputmodel',
            name='input_name',
        ),
        migrations.AddField(
            model_name='inputmodel',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None),
            preserve_default=False,
        ),
    ]